INSERT INTO USERS VALUES ('user1','{noop}pass1',true);
INSERT INTO USERS VALUES ('user2','{noop}pass2',true);

INSERT INTO AUTHORITIES VALUES ('user1','ROLE_USER');
INSERT INTO AUTHORITIES VALUES ('user1','ROLE_ADMIN');
INSERT INTO AUTHORITIES VALUES ('user2','ROLE_USER');
