DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
    USERNAME VARCHAR(250) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(512) NOT NULL,
    ENABLED BOOLEAN NOT NULL
);

DROP TABLE IF EXISTS AUTHORITIES;

CREATE TABLE AUTHORITIES (
    USERNAME VARCHAR(250) NOT NULL,
    AUTHORITY VARCHAR (250) NOT NULL
);